name: "Version Bump"
description: "Automated Commitizen version bump"

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        token: ${{ inputs.github_token }}
