name: "Version Bump"
description: "Automated Commitizen version bump"

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  python-version:
    description: "Python version to use"
    required: false
    default: "3.11"

runs:
  using: composite
  steps: 
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Commitizen
      shell: bash
      run: pip install commitizen

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Bump version
      shell: bash
      run: |
        cz bump --yes --changelog
        cat CHANGELOG.md  # Debug: show what was generated
