name: Version Bump

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - uses: ./.github/actions/commitizen-bump
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

